default_input_parameters:
  nao_max: 26
  nk: 120          # the number of k points
  strcture_name: 'BAND'  # The name of each cif file saved is strcture_name_idx.cif after band calculation
  soc_switch: False
  spin_colinear: False
  auto_mode: True # If the auto_mode is used, users can omit providing k_path and label, as the program will automatically generate them based on the crystal symmetry.
  k_path: [[0.,0.,-0.5],[0.,0.,0.0],[0.,0.,0.5]]
  label: ['$Mbar$','$G$','$M$'] # The lable for each k points in K_path
  save_fig: True
  dpi: 300
  ncpus: 4
  partition: 'chu'
  conda_source: '/ssd/app/anaconda3/etc/profile.d/conda.sh'
  conda_env: 'hamgnn'


